        <link href="/crm/assets/css/IRANSans.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/css/iranyekan.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/css/dana.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/libs/datatables/dataTables.bootstrap4.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/libs/datatables/buttons.bootstrap4.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/libs/datatables/select.bootstrap4.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/css/dropify.min.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/css/jquery.md.bootstrap.datetimepicker.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/css/app-rtl.min.css" rel="stylesheet" type="text/css" />
        <link href="/crm/assets/css/style.css" rel="stylesheet" type="text/css" />